apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-docsapi
  name: stargate-docsapi
spec:
  ports:
  - name: stargate-docsapi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: stargate-docsapi
  type: ClusterIP
status:
  loadBalancer: {}
