version: '2'

services:
  dse:
    image: datastax/dse-server:${DSETAG}
    networks:
      - stargate
    mem_limit: 2G
    environment:
      - MAX_HEAP_SIZE=1536M
      - CLUSTER_NAME=dse-${DSETAG}-cluster
      - DS_LICENSE=accept
    volumes:
      - ${PWD}/dse.yaml:/opt/dse/resources/dse/conf/dse.yaml
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -u cassandra -p cassandra -e 'describe keyspaces'" ]
      interval: 15s
      timeout: 10s
      retries: 20
#
#  data-api:
#    image: ${DATAAPIIMAGE}:${DATAAPITAG}
#    depends_on:
#      coordinator:
#        condition: service_healthy
#    networks:
#      - stargate
#    ports:
#      - "8181:8181"
#    mem_limit: 2G
#    environment:
#      - JAVA_MAX_MEM_RATIO=75
#      - JAVA_INITIAL_MEM_RATIO=50
#      - GC_CONTAINER_OPTIONS=-XX:+UseG1GC
#      - STARGATE_DATA_STORE_IGNORE_BRIDGE=true
#      - STARGATE_JSONAPI_OPERATIONS_DATABASE_CONFIG_CASSANDRA_END_POINTS=coordinator
#      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
#      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
#      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
#    healthcheck:
#      test: curl -f http://localhost:8181/stargate/health || exit 1
#      interval: 5s
#      timeout: 10s
#      retries: 10
networks:
  stargate:
