version: '2'

services:
  coordinator:
    image: stargateio/coordinator-dse-next:${SGTAG}
    networks:
      - stargate
    ports:
      - "9042:9042"
      - "8081:8081"
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx1536M"
      - CLUSTER_NAME=dse-${DSETAG}-cluster
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
      - DEVELOPER_MODE=true
    healthcheck:
      test: curl -f http://localhost:8084/checker/readiness || exit 1
      interval: 15s
      timeout: 10s
      retries: 10

networks:
  stargate:
