version: '2'

services:
  dse-1:
    image: datastax/dse-server:${DSE69TAG}
    platform: linux/amd64
    networks:
      - stargate
    mem_limit: 4G
    environment:
      - MAX_HEAP_SIZE=3G
      - CASSANDRA_CLUSTER_NAME=dse-${DSE69TAG}-cluster
      - DS_LICENSE=accept
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  dse-2:
    image: datastax/dse-server:${DSE69TAG}
    platform: linux/amd64
    networks:
      - stargate
    mem_limit: 4G
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    depends_on:
      dse-1:
        condition: service_healthy
    environment:
      - MAX_HEAP_SIZE=3G
      - CASSANDRA_SEEDS=dse-1
      - CASSANDRA_CLUSTER_NAME=dse-${DSE69TAG}-cluster
      - DS_LICENSE=accept
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  data-api:
    image: ${DATAAPIIMAGE}:${DATAAPITAG}
    depends_on:
      dse-1:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8181:8181"
    mem_limit: 2G
    environment:
      - JAVA_MAX_MEM_RATIO=75
      - JAVA_INITIAL_MEM_RATIO=50
      - STARGATE_DATA_STORE_IGNORE_BRIDGE=true
      - GC_CONTAINER_OPTIONS=-XX:+UseG1GC
      - STARGATE_JSONAPI_OPERATIONS_DATABASE_CONFIG_CASSANDRA_END_POINTS=dse-1
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    healthcheck:
      test: curl -f http://localhost:8181/stargate/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  stargate:
