package io.stargate.sgv2.jsonapi.exception;

/**
 * Errors related to the schema definition in a request.
 *
 * <p>See {@link APIException} for steps to add a new code.
 */
public class SchemaException extends RequestException {

  public static final Scope SCOPE = Scope.SCHEMA;

  public SchemaException(ErrorInstance errorInstance) {
    super(errorInstance);
  }

  public enum Code implements ErrorCode<SchemaException> {
    CANNOT_ADD_EXISTING_COLUMNS,
    CANNOT_ADD_EXISTING_FIELD,
    CANNOT_ADD_EXISTING_INDEX,
    CANNOT_ADD_EXISTING_TABLE,
    CANNOT_ADD_EXISTING_TYPE,
    CANNOT_ADD_UNSUPPORTED_DATA_TYPE_COLUMNS,
    CANNOT_ANALYZE_ENTRIES_ON_MAP_COLUMNS,
    CANNOT_DROP_INDEXED_COLUMNS,
    CANNOT_DROP_PRIMARY_KEY_COLUMNS,
    CANNOT_DROP_TYPE_USED_BY_TABLE,
    CANNOT_DROP_UNKNOWN_COLUMNS,
    CANNOT_DROP_UNKNOWN_INDEX,
    CANNOT_DROP_UNKNOWN_TABLE,
    CANNOT_DROP_UNKNOWN_TYPE,
    CANNOT_DROP_VECTORIZE_FROM_NON_VECTOR_COLUMNS,
    CANNOT_DROP_VECTORIZE_FROM_UNKNOWN_COLUMNS,
    CANNOT_RENAME_UNKNOWN_TYPE_FIELD,
    CANNOT_VECTORIZE_NON_VECTOR_COLUMNS,
    CANNOT_VECTORIZE_UNKNOWN_COLUMNS,
    COLLECTION_NOT_EXIST, // converted from ErrorCodeV1
    DEPRECATED_AI_MODEL,
    EMBEDDING_SERVICE_NOT_CONFIGURED, // converted from ErrorCodeV1
    END_OF_LIFE_AI_MODEL,
    EXISTING_INDEX_FOR_COLLECTION,
    // from ErrorCodeV1 but used by clients DO NOT RENAME:
    EXISTING_COLLECTION_DIFFERENT_SETTINGS,

    EXISTING_TABLE_NOT_DATA_API_COLLECTION, // converted from ErrorCodeV1
    INVALID_CREATE_COLLECTION_OPTIONS,
    INVALID_FORMAT_FOR_INDEX_CREATION_COLUMN,
    INVALID_INDEXING_DEFINITION,
    INVALID_USAGE_OF_VECTORIZE, // legacy: converted from ErrorCodeV1
    INVALID_USER_DEFINED_TYPE_NAME,
    LEXICAL_NOT_AVAILABLE_FOR_DATABASE,
    LEXICAL_NOT_ENABLED_FOR_COLLECTION,
    MISSING_ALTER_TABLE_OPERATIONS,
    MISSING_ALTER_TYPE_OPERATIONS,
    MISSING_DIMENSION_IN_VECTOR_COLUMN,
    MISSING_FIELDS_FOR_TYPE_CREATION,
    MISSING_PARTITION_COLUMNS,

    RERANKING_FEATURE_NOT_ENABLED, // legacy: converted from ErrorCodeV1
    RERANKING_SERVICE_TYPE_UNAVAILABLE, // legacy: converted from ErrorCodeV1
    RERANKING_PROVIDER_UNEXPECTED_RESPONSE, // legacy: converted from ErrorCodeV1

    TOO_MANY_COLLECTIONS, // legacy: converted from ErrorCodeV1
    TOO_MANY_INDEXES_FOR_COLLECTION,
    UNKNOWN_DATA_TYPE,
    UNKNOWN_INDEX_COLUMN,
    UNKNOWN_INDEX_TYPE,
    UNKNOWN_KEYSPACE,
    UNKNOWN_PARTITION_COLUMNS,
    UNKNOWN_PARTITION_SORT_COLUMNS,
    UNKNOWN_PRIMITIVE_DATA_TYPE,
    UNKNOWN_USER_DEFINED_TYPE,
    UNKNOWN_VECTOR_METRIC,
    UNKNOWN_VECTOR_SOURCE_MODEL,
    UNSUPPORTED_DATA_TYPE_TABLE_CREATION,
    UNSUPPORTED_INDEXING_FOR_DATA_TYPES,
    UNSUPPORTED_INDEXING_FOR_FROZEN_COLUMN,
    UNSUPPORTED_INDEX_TYPE,
    UNSUPPORTED_JSON_TYPE_FOR_TEXT_INDEX,
    UNSUPPORTED_LIST_DEFINITION,
    UNSUPPORTED_MAP_DEFINITION,
    UNSUPPORTED_SCHEMA_NAME,
    UNSUPPORTED_SET_DEFINITION,
    UNSUPPORTED_TEXT_ANALYSIS_FOR_DATA_TYPES,
    UNSUPPORTED_TEXT_INDEX_FOR_DATA_TYPES,
    UNSUPPORTED_TYPE_FIELDS,
    UNSUPPORTED_VECTOR_DIMENSION,
    UNSUPPORTED_VECTOR_INDEX_FOR_DATA_TYPES,

    // older below - separated because they need to be confirmed
    INVALID_KEYSPACE,
    INVALID_VECTORIZE_FIELD_CONFIGURATION,
    INVALID_VECTORIZE_TABLE_CONFIGURATION;

    private final ErrorTemplate<SchemaException> template;

    Code() {
      template = ErrorTemplate.load(SchemaException.class, FAMILY, SCOPE, name());
    }

    @Override
    public ErrorTemplate<SchemaException> template() {
      return template;
    }
  }
}
