package io.stargate.sgv2.jsonapi.api.model.command.table;

/** Indicates the origin from which this schema description was generated. */
public enum SchemaDescSource {

  /**
   * Description of a schema object created from an incoming request, such as parsing the table for
   * {@code createTable} or type for {@code createUdt}.
   */
  USER_SCHEMA_OBJECT(false),

  /**
   * Description of schema usage created from an incoming request with {@link #USER_SCHEMA_OBJECT},
   * such as parsing the columns for {@code createTable} or fields for {@code createUdt}.
   */
  USER_SCHEMA_USAGE(false),

  /**
   * Description of a schema object created as the top-level response to a DDL command, such as
   * {@code listTables} or {@code describeTable}.
   */
  DDL_SCHEMA_OBJECT(true),

  /**
   * Description of schema usage created within {@link #DDL_SCHEMA_OBJECT}, such as referencing
   * columns in a table or fields in a type.
   */
  DDL_USAGE(true),

  /**
   * Description of a schema object created as the top-level response to a DML command, such as
   * representing the inline schema for read or write operations.
   */
  DML_SCHEMA_OBJECT(true),

  /**
   * Description of schema usage created within {@link #DML_SCHEMA_OBJECT}, such as referencing
   * columns involved in a read or write operation.
   */
  DML_USAGE(true);

  private final boolean isSystemGenerated;

  SchemaDescSource(boolean isSystemGenerated) {
    this.isSystemGenerated = isSystemGenerated;
  }

  /**
   * True if the schema description source is generated by the system, so from the DB schema, false
   * if it was generated by parsing a user request. If from a user we may not know all the info so
   * may have relaxed rules.
   */
  public boolean isSystemGenerated() {
    return isSystemGenerated;
  }

  /**
   * Helper to create a new {@link UnsupportedOperationException} with a message for when
   * SchemaDescBindingPoint is not supported in a given context.
   *
   * @param context e.g. "ApiTableDef.getSchemaDescription()"
   * @return a new UnsupportedOperationException with a message, throw it yourself :)
   */
  public UnsupportedOperationException unsupportedException(String context) {
    return new UnsupportedOperationException(context + " - unsupported SchemaDescSource: " + this);
  }
}
