apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-jsonapi
  name: stargate-jsonapi
spec:
  ports:
  - name: stargate-jsonapi
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: stargate-jsonapi
  type: ClusterIP
status:
  loadBalancer: {}
