apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-jsonapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: stargate-jsonapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stargate-jsonapi
  template:
    metadata:
      labels:
        app: stargate-jsonapi
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: stargate-jsonapi
              topologyKey: {{ .Values.topologyKey }}
      containers:
        - name: jsonapi
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8181
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.url }}
              port: {{ .Values.probe.readiness.port }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.url }}
              port: {{ .Values.probe.liveness.port }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
          resources:
            requests:
              cpu: {{ .Values.cpu | default 1000 }}m
              memory: {{ .Values.memory | default 1024 }}Mi
          env:
            - name: STARGATE_JSONAPI_OPERATIONS_DATABASE_CONFIG_CASSANDRA_END_POINTS
              value: {{ .Values.cassandraEndPoints }}
            - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_MAXRETRIES
              value: "50"
            - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_MAXDURATION
              value: "300"
            - name: IO_STARGATE_SGV2_API_COMMON_PROPERTIES_DATASTORE_CONFIGURATION_DATASTOREPROPERTIESCONFIGURATION_FETCHSUPPORTEDFEATURES_RETRY_DELAY
              value: "10"
