name: test to generate changelog

# runs on
# * manual trigger
on:
  workflow_dispatch:
  pull_request:

# global env vars, available in all jobs and steps
env:
  MAVEN_OPTS: '-Xmx4g'

jobs:


  # creates a PR for bumping the versions to the next snapshot
  # only executed if we have created the new release
  create-pr:
    name: Version upgrade PR
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Generate changelog
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./update_changelog.sh

      - name: Update version number
        run: |
          ./mvnw -B -ntp release:update-versions -DautoVersionSubmodules=true versions:commit
          ./mvnw -B -ntp xml-format:xml-format fmt:format

      - name: Version bump PR
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN:
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bumping version for the next data-api release"
          title: "Bumping version for next data-api release"
          branch-suffix: "short-commit-hash"
          base: "main"
