name: Publish Docker Image to docker hub

# runs on
# * manual trigger
on:
  workflow_dispatch:

# global env vars, available in all jobs and steps
env:
  MAVEN_OPTS: '-Xmx4g'

jobs:
  # builds and pushes the docker image to docker hub
  main:
    name: Main
    runs-on: ubuntu-latest

    # matrix props:
    strategy:
      matrix:
        type: [ docker, native ]
        include:
          - type: docker
            profile: ''
        exclude:
          - type: native
            #profile: '-Pnative'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push (Docker Hub)
        if: ${{ !inputs.skipPublish }}
        run: |
          ./mvnw -B -ntp clean package -DskipTests -Dquarkus.container-image.build=true -Dquarkus.docker.buildx.platform=linux/amd64,linux/arm64 -Dquarkus.container-image.tag=${{ github.sha }} ${{ matrix.profile }}
          docker push stargateio/jsonapi:${{ github.sha }}
          docker push stargateio/dataapi:${{ github.sha }}