# @author Jeff Carpenter
name: Postman Collection

# runs on
# * schedule (weekly)
# * manual trigger
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:

  # Runs Postman Collection against local Stargate instance using docker compose scripts
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      COLLECTION_ID: 25879866-266032b1-1fe9-4abd-aee9-e6e4b335f921
      ENVIRONMENT_ID: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Start Backend
        # Run Stargate coordinator in developer mode to save time / resources
        run: |
          cd docker-compose
          ./start_dse_68_dev_mode.sh
      - name: Run API test
        run: |
          postman collection run $COLLECTION_ID -e $ENVIRONMENT_ID --verbose
      - name: Stop Backend
        if: always()
        run: |
          cd docker-compose
          docker compose logs jsonapi
          docker compose -f docker-compose-dev-mode.yml down

